version: "3.9"  # optional since v1.27.0
services:
  tibber_prices:
    image: areskiko/tibber_status:${PLATFORM}
    restart: always

    # Needed to pass token if not set as environment variables
    tty: true
    stdin_open: true

    volumes:
      # Easier access to logs
      - tibber_prices_logvolume:/var/log/
      - tibber_credentials:/credentials/
    
    # Settings
    environment:
      - INFLUXDB_ADDR=http://192.168.10.102:8086
      - INFLUXDB_DB_NAME=Fibaro
      - TIBBER_API_ENDPOINT=https://api.tibber.com/v1-beta/gql
      - LOG_LEVEL=info # defaults to info
      - TOKEN_FILE=/credentials/credentials
      - RETRIES = 13
  
  tibber_refiner:
    image: areskiko/tibber_refiner:${PLATFORM}
    restart: always

    # Needed to pass token if not set as environment variables
    tty: true
    stdin_open: true

    volumes:
      # Easier access to logs
      - tibber_refiner_logvolume:/var/log/
      - tibber_credentials:/credentials/
    
    # Settings
    environment:
      - INFLUXDB_ADDR=http://192.168.10.102:8086
      - INFLUXDB_DB_NAME=Fibaro
      - LOG_LEVEL=info # defaults to info
      - TOKEN_FILE=/credentials/credentials
      - RETRIES = 13
  
  tibber_subscribe:
    image: areskiko/tibber_subscribe:${PLATFORM}
    restart: always

    # Needed to pass username and password if not set as environment variables
    tty: true
    stdin_open: true

    volumes:
      - tibber_subscribe_logvolume:/var/log/
      - tibber_credentials:/credentials/
    environment:
      - INFLUXDB_ADDR=http://192.168.10.102:8086
      - INFLUXDB_DB_NAME=Fibaro
      - TIBBER_API_ENDPOINT=wss://api.tibber.com/v1-beta/gql/subscriptions
      - HOME_ID=36231b62-0d4a-43cc-a210-c147b2cc97dc
      - LOG_LEVEL=info # defaults to info
      - TOKEN_FILE=/credentials/credentials

  easee:
    image: areskiko/easee_status:${PLATFORM}
    restart: always

    # Needed to pass username and password if not set as environment variables
    tty: true
    stdin_open: true

    volumes:
      # Easier access to logs
      - easee_logvolume:/var/log/
      - easee_credentials:/credentials/
    
    # Settings
    environment:
      - INFLUXDB_ADDR=http://192.168.10.102:8086
      - INFLUXDB_DB_NAME=Fibaro
      - LOG_LEVEL=info # defaults to info
      - CREDENTIALS_FILE=/credentials/credentials
      - INTERVAL=1 # defaults to 1
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60

volumes:
  tibber_credentials: {}
  easee_credentials: {}
  tibber_prices_logvolume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/log/CasaMack/tibber_prices'
  tibber_refiner_logvolume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/log/CasaMack/tibber_refiner'
  tibber_subscribe_logvolume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/log/CasaMack/tibber_subscribe'
  easee_logvolume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/log/CasaMack/easee'
